import asyncio
from sqlalchemy import select
from database import async_session, init_db
from main import AllergenORM, FoodItemORM

COMMON_ALLERGENS = [
    ("Peanuts", "Legume allergen"),
    ("Tree Nuts", "Almonds, walnuts, cashews, etc."),
    ("Milk", "Dairy products containing lactose"),
    ("Eggs", "Egg whites and yolks"),
    ("Wheat", "Gluten-containing grain"),
    ("Soy", "Soybeans and soy products"),
    ("Fish", "Salmon, tuna, cod, etc."),
    ("Shellfish", "Shrimp, crab, lobster"),
    ("Sesame", "Sesame seeds and oil"),
    ("Mustard", "Mustard seeds and condiment"),
    ("Celery", "Celery stalks and leaves"),
    ("Sulfites", "Preservatives in wine and dried fruit"),
    ("Lupin", "Lupin flour and seeds"),
    ("Molluscs", "Clams, mussels, oysters"),
    ("Gluten", "Protein in wheat, barley, rye"),
    ("Lactose", "Milk sugar"),
    ("Corn", "Maize and corn products"),
    ("Coconut", "Coconut flesh and milk"),
    ("Avocado", "Avocado fruit"),
    ("Kiwi", "Kiwi fruit"),
    ("Banana", "Banana fruit"),
    ("Strawberry", "Strawberry fruit"),
    ("Chocolate", "Cocoa and chocolate products"),
    ("Caffeine", "Coffee and tea stimulant"),
    ("Alcohol", "Ethanol in beverages"),
    ("Yeast", "Baker's and brewer's yeast"),
    ("Mushrooms", "Fungi and mushrooms"),
    ("Nitrates", "Preservatives in processed meats"),
    ("Artificial colors", "Synthetic food dyes"),
    ("Artificial flavors", "Synthetic flavor additives"),
    ("MSG", "Monosodium glutamate"),
    ("Garlic", "Garlic bulb and powder"),
    ("Onion", "Onion bulb and powder"),
    ("Rice", "Rice grain"),
    ("Potato", "Potato tuber"),
    ("Tomato", "Tomato fruit"),
    ("Bell pepper", "Pepper fruit"),
    ("Citrus", "Orange, lemon, lime, grapefruit"),
    ("Pineapple", "Pineapple fruit"),
    ("Mango", "Mango fruit"),
    ("Grape", "Grape fruit"),
    ("Peach", "Peach fruit"),
    ("Apple", "Apple fruit"),
    ("Pear", "Pear fruit"),
    ("Almond", "Tree nut"),
    ("Hazelnut", "Tree nut"),
    ("Walnut", "Tree nut"),
    ("Cashew", "Tree nut"),
    ("Pistachio", "Tree nut"),
    ("Macadamia", "Tree nut"),
    ("Brazil nut", "Tree nut"),
    ("Pecan", "Tree nut"),
    ("Sunflower seed", "Seed"),
    ("Pumpkin seed", "Seed"),
    ("Flaxseed", "Seed"),
    ("Chia seed", "Seed"),
    ("Hemp seed", "Seed"),
    ("Poppy seed", "Seed"),
    ("Sesame seed", "Seed"),
    ("Mustard seed", "Seed"),
    ("Cinnamon", "Spice"),
    ("Nutmeg", "Spice"),
    ("Vanilla", "Spice/extract"),
    ("Ginger", "Spice/root"),
    ("Turmeric", "Spice/root"),
    ("Cumin", "Spice"),
    ("Coriander", "Spice/herb"),
    ("Basil", "Herb"),
    ("Oregano", "Herb"),
    ("Thyme", "Herb"),
    ("Rosemary", "Herb"),
    ("Sage", "Herb"),
    ("Mint", "Herb"),
    ("Parsley", "Herb"),
    ("Cilantro", "Herb"),
    ("Dill", "Herb"),
    ("Chili", "Spice/pepper"),
    ("Paprika", "Spice/pepper"),
    ("Cayenne", "Spice/pepper"),
    ("Black pepper", "Spice/pepper"),
    ("Cardamom", "Spice"),
    ("Clove", "Spice"),
    ("Star anise", "Spice"),
    ("Licorice", "Root/extract"),
    ("Tamarind", "Fruit/pulp"),
    ("Wasabi", "Japanese horseradish"),
    ("Horseradish", "Root/condiment"),
    ("Leek", "Allium vegetable"),
    ("Shallot", "Allium vegetable"),
    ("Chive", "Allium herb"),
    ("Scallion", "Allium vegetable"),
    ("Green onion", "Allium vegetable"),
    ("Spring onion", "Allium vegetable"),
    ("Red onion", "Allium vegetable"),
    ("Yellow onion", "Allium vegetable"),
    ("Sweet onion", "Allium vegetable"),
    ("White onion", "Allium vegetable"),
    ("Onion powder", "Dehydrated onion"),
    ("Garlic powder", "Dehydrated garlic"),
    ("Garlic salt", "Garlic and salt mixture"),
    ("Onion salt", "Onion and salt mixture"),
    ("Seasoning salt", "Mixed seasoning"),
    ("Celery salt", "Celery and salt mixture"),
    ("Olive", "Olive fruit"),
    ("Olive oil", "Olive oil"),
    ("Sunflower oil", "Vegetable oil"),
    ("Canola oil", "Vegetable oil"),
    ("Vegetable oil", "Mixed vegetable oil"),
    ("Palm oil", "Palm fruit oil"),
    ("Coconut oil", "Coconut oil"),
    ("Peanut oil", "Peanut oil"),
    ("Sesame oil", "Sesame oil"),
    ("Soy oil", "Soybean oil"),
    ("Corn oil", "Corn oil"),
    ("Grapeseed oil", "Grape oil"),
    ("Avocado oil", "Avocado oil"),
    ("Walnut oil", "Walnut oil"),
    ("Almond oil", "Almond oil"),
    ("Hazelnut oil", "Hazelnut oil"),
    ("Macadamia oil", "Macadamia oil"),
    ("Flax oil", "Flaxseed oil"),
    ("Hemp oil", "Hemp oil"),
    ("Pumpkin oil", "Pumpkin seed oil"),
    ("Safflower oil", "Safflower oil"),
    ("Rice bran oil", "Rice bran oil"),
    ("Wheat germ oil", "Wheat germ oil"),
    ("Butter", "Dairy fat"),
    ("Ghee", "Clarified butter"),
    ("Margarine", "Butter substitute"),
    ("Shortening", "Fat for baking"),
    ("Lard", "Pork fat"),
    ("Tallow", "Beef fat"),
    ("Suet", "Hard fat"),
    ("Cream", "Dairy cream"),
    ("Whipped cream", "Whipped dairy cream"),
    ("Sour cream", "Fermented dairy cream"),
    ("Crème fraîche", "French cultured cream"),
    ("Mascarpone", "Italian cream cheese"),
    ("Ricotta", "Italian whey cheese"),
    ("Cottage cheese", "Fresh cheese curd"),
    ("Feta", "Greek brined cheese"),
    ("Mozzarella", "Italian soft cheese"),
    ("Cheddar", "English hard cheese"),
    ("Parmesan", "Italian hard cheese"),
    ("Gouda", "Dutch cheese"),
    ("Brie", "French soft cheese"),
    ("Camembert", "French soft cheese"),
    ("Roquefort", "French blue cheese"),
    ("Blue cheese", "Cheese with mold"),
    ("Gorgonzola", "Italian blue cheese"),
    ("Stilton", "English blue cheese"),
    ("Halloumi", "Cypriot cheese"),
    ("Paneer", "Indian fresh cheese"),
    ("Queso fresco", "Fresh cheese"),
    ("Queso blanco", "White cheese"),
    ("Cream cheese", "Soft cheese spread"),
    ("Neufchâtel", "French soft cheese"),
    ("Whey", "Milk byproduct"),
    ("Whey protein", "Protein from whey"),
    ("Whey powder", "Dried whey"),
    ("Whey isolate", "Purified whey protein"),
    ("Whey concentrate", "Concentrated whey protein"),
    ("Casein", "Milk protein"),
    ("Caseinate", "Casein salt"),
    ("Sodium caseinate", "Sodium casein salt"),
    ("Calcium caseinate", "Calcium casein salt"),
    ("Milk protein", "Protein from milk"),
    ("Milk solids", "Dried milk components"),
    ("Nonfat milk", "Skim milk powder"),
    ("Skim milk", "Fat-free milk"),
    ("Whole milk", "Full-fat milk"),
    ("Evaporated milk", "Concentrated milk"),
    ("Condensed milk", "Sweetened concentrated milk"),
    ("Sweetened condensed milk", "Sugar-added milk concentrate"),
    ("Dried milk", "Milk powder"),
    ("Powdered milk", "Dehydrated milk"),
    ("Milk powder", "Dried milk"),
    ("Milk derivative", "Milk-based ingredient"),
    ("Milk fat", "Fat from milk"),
    ("Butter oil", "Milk fat oil"),
    ("Butterfat", "Milk fat"),
    ("Anhydrous milk fat", "Concentrated milk fat"),
    ("Clarified butter", "Butter with water removed"),
    ("Lactalbumin", "Whey protein"),
    ("Lactalbumin phosphate", "Lactalbumin derivative"),
    ("Lactoglobulin", "Whey protein"),
    ("Lactoferrin", "Milk protein"),
    ("Lactose", "Milk sugar"),
    ("Lactitol", "Sugar alcohol from lactose"),
    ("Lactulose", "Synthetic disaccharide"),
    ("Lactic acid", "Acid from fermentation"),
    ("Lactate", "Lactic acid salt"),
    ("Sodium lactate", "Sodium lactate salt"),
    ("Calcium lactate", "Calcium lactate salt"),
    ("Potassium lactate", "Potassium lactate salt"),
    ("Ammonium lactate", "Ammonium lactate salt"),
    ("Galactose", "Milk sugar component"),
    ("Tagatose", "Natural sweetener"),
    ("Ghee butter", "Clarified butter"),
    ("Kefir", "Fermented milk drink"),
    ("Yogurt", "Fermented milk"),
    ("Greek yogurt", "Strained yogurt"),
    ("Skyr", "Icelandic yogurt"),
    ("Buttermilk", "Fermented milk"),
    ("Ayran", "Turkish yogurt drink"),
    ("Lassi", "Indian yogurt drink"),
    ("Kumis", "Fermented mare milk"),
    ("Clabber", "Fermented milk"),
    ("Curds", "Milk curds"),
    ("Milk curd", "Coagulated milk"),
    ("Rennet", "Enzyme for cheese making"),
    ("Rennet casein", "Casein from rennet"),
    ("Acid casein", "Casein from acid"),
    ("Goat milk", "Milk from goats"),
    ("Sheep milk", "Milk from sheep"),
    ("Buffalo milk", "Milk from buffalo"),
    ("Camel milk", "Milk from camels"),
    ("Yak milk", "Milk from yaks"),
    ("Horse milk", "Milk from horses"),
    ("Donkey milk", "Milk from donkeys"),
    ("Reindeer milk", "Milk from reindeer"),
    ("Moose milk", "Milk from moose"),
    ("Seal milk", "Milk from seals"),
    ("Whale milk", "Milk from whales"),
    ("Dolphin milk", "Milk from dolphins"),
    ("Human milk", "Breast milk"),
    ("Breast milk", "Human milk"),
    ("Colostrum", "First milk"),
    ("Egg white", "Albumen"),
    ("Egg yolk", "Vitellus"),
    ("Egg powder", "Dried eggs"),
    ("Dried egg", "Dehydrated egg"),
    ("Egg solids", "Dried egg components"),
    ("Egg protein", "Protein from eggs"),
    ("Albumin", "Egg white protein"),
    ("Albumen", "Egg white"),
    ("Ovalbumin", "Main egg white protein"),
    ("Ovomucoid", "Egg white protein"),
    ("Ovomucin", "Egg white protein"),
    ("Ovovitellin", "Egg yolk protein"),
    ("Lysozyme", "Egg white enzyme"),
    ("Lecithin", "Egg yolk phospholipid"),
    ("Egg lecithin", "Lecithin from eggs"),
    ("Egg glaze", "Egg wash coating"),
    ("Egg wash", "Egg coating for baking"),
    ("Eggnog", "Egg and milk drink"),
    ("Mayonnaise", "Egg-based condiment"),
    ("Hollandaise", "Egg-based sauce"),
    ("Meringue", "Whipped egg whites"),
    ("Custard", "Egg and milk dessert"),
    ("Flan", "Egg custard dessert"),
    ("Crème brûlée", "Egg custard dessert"),
    ("Tiramisu", "Italian dessert with eggs"),
    ("Zabaglione", "Italian egg dessert"),
    ("Sabayon", "French egg dessert"),
    ("Pavlova", "Meringue dessert"),
    ("Angel food cake", "Egg white cake"),
    ("Soufflé", "Egg-based dish"),
    ("Frittata", "Italian egg dish"),
    ("Quiche", "French egg tart"),
    ("Omelet", "Folded egg dish"),
    ("Scrambled eggs", "Stirred eggs"),
    ("Boiled egg", "Hard or soft boiled egg"),
    ("Poached egg", "Egg cooked in water"),
    ("Fried egg", "Pan-fried egg"),
    ("Hard-boiled egg", "Fully cooked egg"),
    ("Soft-boiled egg", "Partially cooked egg"),
    ("Pickled egg", "Egg in brine"),
    ("Century egg", "Preserved duck egg"),
    ("Salted egg", "Brined duck egg"),
    ("Duck egg", "Egg from ducks"),
    ("Quail egg", "Egg from quails"),
    ("Turkey egg", "Egg from turkeys"),
    ("Goose egg", "Egg from geese"),
    ("Pheasant egg", "Egg from pheasants"),
    ("Ostrich egg", "Egg from ostriches"),
    ("Emu egg", "Egg from emus"),
    ("Caviar", "Fish roe"),
    ("Roe", "Fish eggs"),
    ("Fish roe", "Fish eggs"),
    ("Salmon roe", "Salmon eggs"),
    ("Trout roe", "Trout eggs"),
    ("Whitefish roe", "Whitefish eggs"),
    ("Lumpfish roe", "Lumpfish eggs"),
    ("Tobiko", "Flying fish roe"),
    ("Masago", "Capelin roe"),
    ("Ikura", "Salmon roe"),
    ("Karashi mentaiko", "Spicy cod roe"),
    ("Tarako", "Salted cod roe"),
    ("Cod roe", "Cod eggs"),
    ("Herring roe", "Herring eggs"),
    ("Sturgeon roe", "Sturgeon eggs"),
    ("Beluga caviar", "Sturgeon roe"),
    ("Osetra caviar", "Sturgeon roe"),
    ("Sevruga caviar", "Sturgeon roe"),
    ("Sterlet caviar", "Sturgeon roe"),
    ("Hackleback caviar", "Shovelnose sturgeon roe"),
    ("Paddlefish caviar", "Paddlefish roe"),
    ("Bowfin caviar", "Bowfin roe"),
    ("Salmon caviar", "Salmon roe"),
    ("Trout caviar", "Trout roe"),
    ("Whitefish caviar", "Whitefish roe"),
    ("Lumpfish caviar", "Lumpfish roe"),
    ("Flying fish roe", "Tobiko"),
    ("Capelin roe", "Masago"),
    ("Pollock roe", "Pollock eggs"),
    ("Haddock roe", "Haddock eggs"),
    ("Cod liver", "Cod liver"),
    ("Fish liver", "Fish liver"),
    ("Fish oil", "Oil from fish"),
    ("Cod liver oil", "Oil from cod liver"),
    ("Shark liver oil", "Oil from shark liver"),
    ("Squalene", "Shark liver oil component"),
    ("Squalane", "Hydrogenated squalene"),
    ("Isinglass", "Fish bladder gelatin"),
    ("Fish gelatin", "Gelatin from fish"),
    ("Fish stock", "Broth from fish"),
    ("Fish sauce", "Fermented fish condiment"),
    ("Oyster sauce", "Oyster-based condiment"),
    ("Worcestershire sauce", "Fermented sauce with anchovy"),
    ("Anchovy", "Small fish"),
    ("Anchovy paste", "Anchovy paste"),
    ("Fish paste", "Fermented fish paste"),
    ("Shrimp paste", "Fermented shrimp paste"),
    ("Crab paste", "Crab-based paste"),
    ("Lobster paste", "Lobster-based paste"),
    ("Bottarga", "Dried fish roe"),
    ("Tuna", "Tuna fish"),
    ("Salmon", "Salmon fish"),
    ("Mackerel", "Mackerel fish"),
    ("Sardine", "Sardine fish"),
    ("Herring", "Herring fish"),
    ("Swordfish", "Swordfish"),
    ("Marlin", "Marlin fish"),
    ("Shark", "Shark fish"),
    ("Ray", "Ray fish"),
    ("Skate", "Skate fish"),
    ("Catfish", "Catfish"),
    ("Tilapia", "Tilapia fish"),
    ("Cod", "Cod fish"),
    ("Haddock", "Haddock fish"),
    ("Pollock", "Pollock fish"),
    ("Hake", "Hake fish"),
    ("Whiting", "Whiting fish"),
    ("Coley", "Saithe fish"),
    ("Ling", "Ling fish"),
    ("Blue whiting", "Blue whiting fish"),
    ("Southern blue whiting", "Southern blue whiting fish"),
    ("Saithe", "Coalfish"),
    ("Hoki", "Hoki fish"),
    ("Orange roughy", "Orange roughy fish"),
    ("Patagonian toothfish", "Chilean sea bass"),
    ("Chilean sea bass", "Patagonian toothfish"),
    ("Grouper", "Grouper fish"),
    ("Sea bass", "Bass fish"),
    ("Bass", "Bass fish"),
    ("Perch", "Perch fish"),
    ("Zander", "Zander fish"),
    ("Pike", "Pike fish"),
    ("Walleye", "Walleye fish"),
    ("Muskellunge", "Muskie fish"),
    ("Barramundi", "Barramundi fish"),
    ("Snakehead", "Snakehead fish"),
    ("Tench", "Tench fish"),
    ("Carp", "Carp fish"),
    ("Goldfish", "Goldfish"),
    ("Koi", "Koi fish"),
    ("Guppy", "Guppy fish"),
    ("Molly", "Molly fish"),
    ("Platy", "Platy fish"),
    ("Swordtail", "Swordtail fish"),
    ("Tetra", "Tetra fish"),
    ("Danio", "Danio fish"),
    ("Barb", "Barb fish"),
    ("Rasbora", "Rasbora fish"),
    ("Loach", "Loach fish"),
    ("Corydoras", "Corydoras fish"),
    ("Pleco", "Plecostomus fish"),
    ("Otocinclus", "Oto fish"),
    ("Amano shrimp", "Amano shrimp"),
    ("Cherry shrimp", "Cherry shrimp"),
    ("Ghost shrimp", "Ghost shrimp"),
    ("Crystal red shrimp", "Crystal red shrimp"),
    ("Bee shrimp", "Bee shrimp"),
    ("Tiger shrimp", "Tiger shrimp"),
    ("Ninja shrimp", "Ninja shrimp"),
    ("Bamboo shrimp", "Bamboo shrimp"),
    ("Vampire shrimp", "Vampire shrimp"),
    ("Malaysian trumpet snail", "Malaysian trumpet snail"),
    ("Nerite snail", "Nerite snail"),
    ("Mystery snail", "Mystery snail"),
    ("Ramshorn snail", "Ramshorn snail"),
    ("Bladder snail", "Bladder snail"),
    ("Pond snail", "Pond snail"),
    ("Apple snail", "Apple snail"),
    ("Assassin snail", "Assassin snail"),
    ("Rabbit snail", "Rabbit snail"),
    ("Trumpet snail", "Trumpet snail"),
    ("Tadpole snail", "Tadpole snail"),
    ("Planorbis", "Ramshorn snail genus"),
    ("Physella", "Bladder snail genus"),
    ("Lymnaea", "Pond snail genus"),
    ("Melanoides", "Trumpet snail genus"),
    ("Neritina", "Nerite snail genus"),
    ("Clithon", "Nerite snail genus"),
    ("Septaria", "Nerite snail genus"),
    ("Vittina", "Nerite snail genus"),
    ("Neripteron", "Nerite snail genus"),
    ("Anentome", "Assassin snail genus"),
    ("Clea", "Assassin snail genus"),
    ("Faunus", "Snail genus"),
    ("Sulcospira", "Snail genus"),
    ("Brotia", "Snail genus"),
    ("Stenomelania", "Snail genus"),
    ("Thiara", "Snail genus"),
    ("Tarebia", "Snail genus"),
    ("Indoplanorbis", "Snail genus"),
    ("Gyraulus", "Snail genus"),
    ("Helisoma", "Snail genus"),
    ("Biomphalaria", "Snail genus"),
    ("Bulinus", "Snail genus"),
    ("Oncomelania", "Snail genus"),
    ("Pomacea", "Apple snail genus"),
    ("Marisa", "Apple snail genus"),
    ("Ampullaria", "Apple snail genus"),
    ("Pila", "Apple snail genus"),
    ("Lanistes", "Snail genus"),
    ("Bellamya", "Snail genus"),
    ("Cipangopaludina", "Snail genus"),
    ("Sinotaia", "Snail genus"),
    ("Viviparus", "Snail genus"),
    ("Filopaludina", "Snail genus"),
    ("Idiopoma", "Snail genus"),
    ("Turbo", "Turbo snail genus"),
    ("Trochus", "Trochus snail genus"),
    ("Haliotis", "Abalone genus"),
    ("Abalone", "Sea snail"),
    ("Ormer", "European abalone"),
    ("Paua", "New Zealand abalone"),
    ("Mother-of-pearl", "Nacre shell"),
    ("Nacre", "Mother-of-pearl"),
    ("Mabe pearl", "Blister pearl"),
    ("Keshi pearl", "Seedless pearl"),
    ("Biwa pearl", "Freshwater pearl"),
    ("South Sea pearl", "Large pearl"),
    ("Tahitian pearl", "Black pearl"),
    ("Akoya pearl", "Japanese pearl"),
    ("Freshwater pearl", "Freshwater pearl"),
    ("Cultured pearl", "Cultivated pearl"),
    ("Natural pearl", "Natural pearl"),
    ("Imitation pearl", "Synthetic pearl"),
    ("Shell button", "Button from shell"),
    ("Shell bead", "Bead from shell"),
    ("Shell inlay", "Inlay from shell"),
    ("Mother-of-pearl button", "Button from nacre"),
    ("Shell powder", "Powdered shell"),
    ("Calcium carbonate", "Shell mineral"),
    ("Aragonite", "Calcium carbonate mineral"),
    ("Calcite", "Calcium carbonate mineral"),
    ("Vaterite", "Calcium carbonate mineral"),
    ("Calcium oxide", "Quicklime"),
    ("Calcium hydroxide", "Slaked lime"),
    ("Calcium phosphate", "Bone mineral"),
    ("Calcium sulfate", "Gypsum"),
    ("Calcium chloride", "Calcium salt"),
    ("Calcium citrate", "Calcium supplement"),
    ("Calcium gluconate", "Calcium supplement"),
    ("Calcium lactate", "Calcium salt"),
    ("Calcium malate", "Calcium supplement"),
    ("Calcium orotate", "Calcium supplement"),
    ("Calcium pidolate", "Calcium supplement"),
    ("Calcium acetate", "Calcium salt"),
    ("Calcium ascorbate", "Calcium vitamin C"),
    ("Calcium aspartate", "Calcium supplement"),
    ("Calcium bisglycinate", "Calcium supplement"),
    ("Calcium carbonate", "Calcium supplement"),
    ("Calcium caseinate", "Calcium milk protein"),
    ("Calcium chelate", "Chelated calcium"),
    ("Calcium citrate malate", "Calcium supplement"),
    ("Calcium complex", "Calcium compound"),
    ("Calcium coral", "Coral calcium"),
    ("Calcium disodium EDTA", "Calcium chelator"),
    ("Calcium D-saccharate", "Calcium salt"),
    ("Calcium ferrocyanide", "Calcium salt"),
    ("Calcium fluoride", "Calcium salt"),
    ("Calcium folinate", "Calcium folate"),
    ("Calcium formate", "Calcium salt"),
    ("Calcium fructoborate", "Calcium supplement"),
    ("Calcium fumarate", "Calcium supplement"),
    ("Calcium glycerophosphate", "Calcium supplement"),
    ("Calcium glycinate", "Calcium supplement"),
    ("Calcium heptonate", "Calcium supplement"),
    ("Calcium hexametaphosphate", "Calcium phosphate"),
    ("Calcium hypochlorite", "Bleaching agent"),
    ("Calcium iodate", "Iodine source"),
    ("Calcium lactobionate", "Calcium salt"),
    ("Calcium laurate", "Calcium soap"),
    ("Calcium levulinate", "Calcium salt"),
    ("Calcium lignosulfonate", "Calcium salt"),
    ("Calcium molybdate", "Calcium salt"),
    ("Calcium nitrate", "Fertilizer"),
    ("Calcium pantothenate", "Vitamin B5 calcium"),
    ("Calcium peroxide", "Oxygen source"),
    ("Calcium phytate", "Calcium salt"),
    ("Calcium propionate", "Preservative"),
    ("Calcium pyrophosphate", "Calcium phosphate"),
    ("Calcium pyruvate", "Calcium supplement"),
    ("Calcium saccharate", "Calcium salt"),
    ("Calcium silicate", "Anti-caking agent"),
    ("Calcium sorbate", "Preservative"),
    ("Calcium stearate", "Lubricant"),
    ("Calcium stearyl lactylate", "Emulsifier"),
    ("Calcium sulfate", "Gypsum"),
    ("Calcium sulfite", "Preservative"),
    ("Calcium tartrate", "Calcium salt"),
    ("Calcium taurate", "Calcium supplement"),
    ("Calcium thiosulfate", "Calcium salt"),
    ("Calcium threonate", "Calcium supplement"),
    ("Calcium undecylenate", "Calcium salt"),
    ("Calcium saccharin", "Sweetener salt"),
    ("Calcium sodium caseinate", "Milk protein salt"),
    ("Calcium stearoyl lactylate", "Emulsifier"),
    ("Calcium AKG", "Alpha-ketoglutarate"),
    ("Calcium D-glucarate", "Calcium supplement"),
    ("Calcium GABA", "Neurotransmitter supplement"),
    ("Calcium HMB", "Beta-hydroxy beta-methylbutyrate"),
    ("Calcium L-5-MTHF", "Folate supplement"),
    ("Calcium L-carnitine", "Carnitine supplement"),
    ("Calcium L-lysine", "Lysine supplement"),
    ("Calcium L-threonate", "Threonate supplement"),
    ("Calcium magnesium", "Combined supplement"),
    ("Calcium succinate", "Calcium supplement"),
    ("Calcium theanate", "Theanine supplement"),
    ("Calcium alpha-ketoglutarate", "AKG supplement"),
    ("Calcium ascorbate", "Vitamin C calcium"),
    ("Calcium aspartate", "Calcium supplement"),
    ("Calcium bisglycinate", "Calcium supplement"),
    ("Calcium carbonate", "Calcium supplement"),
    ("Calcium chloride", "Calcium salt"),
    ("Calcium citrate", "Calcium supplement"),
    ("Calcium gluconate", "Calcium supplement"),
    ("Calcium glycinate", "Calcium supplement"),
    ("Calcium hydroxide", "Slaked lime"),
    ("Calcium lactate", "Calcium salt"),
    ("Calcium malate", "Calcium supplement"),
    ("Calcium orotate", "Calcium supplement"),
    ("Calcium oxide", "Quicklime"),
    ("Calcium phosphate", "Bone mineral"),
    ("Calcium pidolate", "Calcium supplement"),
    ("Calcium stearate", "Lubricant"),
    ("Calcium sulfate", "Gypsum"),
    ("Calcium taurate", "Calcium supplement"),
    ("Calcium threonate", "Calcium supplement"),
]

async def seed_allergens():
    async with async_session() as db:
        result = await db.execute(select(AllergenORM))
        existing = {a.name for a in result.scalars().all()}
        
        # Deduplicate the list, keeping first occurrence
        seen = set()
        unique_allergens = []
        for name, desc in COMMON_ALLERGENS:
            if name not in seen:
                seen.add(name)
                unique_allergens.append((name, desc))
        
        new_count = 0
        for name, desc in unique_allergens:
            if name not in existing:
                allergen = AllergenORM(name=name, description=desc)
                db.add(allergen)
                new_count += 1
        
        if new_count > 0:
            await db.commit()
            print(f"Inserted {new_count} new allergens.")
        else:
            print("Allergens already seeded.")
        
        # Count total
        result = await db.execute(select(AllergenORM))
        total = len(result.scalars().all())
        print(f"Total allergens in database: {total}")

if __name__ == "__main__":
    asyncio.run(seed_allergens())
