"""add restaurants, users, and restaurant_id multi-tenant columns

Revision ID: 284660d2ac6f
Revises: 
Create Date: 2026-07-26 18:30:21.001045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284660d2ac6f'
down_revision: Union[str, Sequence[str], None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('join_code', sa.String(), nullable=False),
    sa.Column('admin_pin_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.create_index(op.f('ix_restaurants_join_code'), 'restaurants', ['join_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'staff', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_restaurant_id'), 'users', ['restaurant_id'], unique=False)

    # Backfill: assign any pre-existing (pre-multi-tenant) rows to a "legacy" restaurant
    # instead of dropping them, so local/dev data survives the migration.
    connection = op.get_bind()
    legacy_restaurant_id = connection.execute(sa.text(
        "INSERT INTO restaurants (name, join_code, admin_pin_hash) "
        "VALUES ('Legacy Restaurant', 'LEGACY-0000', '') RETURNING id"
    )).scalar()

    op.add_column('allergens', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    connection.execute(sa.text("UPDATE allergens SET restaurant_id = :rid").bindparams(rid=legacy_restaurant_id))
    op.alter_column('allergens', 'restaurant_id', nullable=False)
    op.drop_index(op.f('ix_allergens_name'), table_name='allergens')
    op.create_index(op.f('ix_allergens_name'), 'allergens', ['name'], unique=False)
    op.create_index(op.f('ix_allergens_restaurant_id'), 'allergens', ['restaurant_id'], unique=False)
    op.create_unique_constraint('uq_allergen_restaurant_name', 'allergens', ['restaurant_id', 'name'])
    op.create_foreign_key(None, 'allergens', 'restaurants', ['restaurant_id'], ['id'])

    op.add_column('food_items', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    connection.execute(sa.text("UPDATE food_items SET restaurant_id = :rid").bindparams(rid=legacy_restaurant_id))
    op.alter_column('food_items', 'restaurant_id', nullable=False)
    op.create_index(op.f('ix_food_items_restaurant_id'), 'food_items', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'food_items', 'restaurants', ['restaurant_id'], ['id'])

    op.add_column('recipes', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    connection.execute(sa.text("UPDATE recipes SET restaurant_id = :rid").bindparams(rid=legacy_restaurant_id))
    op.alter_column('recipes', 'restaurant_id', nullable=False)
    op.create_index(op.f('ix_recipes_restaurant_id'), 'recipes', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'recipes', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_index(op.f('ix_recipes_restaurant_id'), table_name='recipes')
    op.drop_column('recipes', 'restaurant_id')
    op.drop_constraint(None, 'food_items', type_='foreignkey')
    op.drop_index(op.f('ix_food_items_restaurant_id'), table_name='food_items')
    op.drop_column('food_items', 'restaurant_id')
    op.drop_constraint(None, 'allergens', type_='foreignkey')
    op.drop_constraint('uq_allergen_restaurant_name', 'allergens', type_='unique')
    op.drop_index(op.f('ix_allergens_restaurant_id'), table_name='allergens')
    op.drop_index(op.f('ix_allergens_name'), table_name='allergens')
    op.create_index(op.f('ix_allergens_name'), 'allergens', ['name'], unique=True)
    op.drop_column('allergens', 'restaurant_id')
    op.drop_index(op.f('ix_users_restaurant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_restaurants_join_code'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
